### ISSUE TITLE
Implement auto-publishing new dev dists to Test PyPI on each push to master

### ISSUE THREAD

**Issue by webknjaz** [aio-libs/create-aio-app#110]
Cutting-edge example:
- https://github.com/sanitizers/octomachinery/blob/f7f023d/.travis.yml#L53-L65
- https://github.com/sanitizers/octomachinery/blob/f7f023d/setup.cfg#L9
- https://github.com/sanitizers/octomachinery/blob/f7f023d/octomachinery/utils/versiontools.py#L9-L38

**Comment by MaxTyulin** [comment]
Are the login and password for test.pypi will be the same as for production pypi?

**Comment by webknjaz** [comment]
No, the TestPyPI account is completely separate.
