### ISSUE TITLE
Remove cookiecutter.json file from project_new

### ISSUE THREAD

**Issue by HelenShy** [aio-libs/create-aio-app#114]
Cookiecutter.json file does not need to be generated in project_new folder.

**Comment by Sanyen** [comment]
Hello there folks, just for clarification: Are we looking to generate the cookiecutter.json file in a different directory?

**Comment by Arfey** [comment]
Hi 👋

After create project via create-aio-app in project we have cookiecutter.json, but this file need only for generation and don't need in project. So task is remove this file in generated project.

**Comment by Sanyen** [comment]
Hello there @Arfey,

I will take a crack at it.

**Comment by Sanyen** [comment]
@Arfey i tried a thing. First pull request, so not sure if everything was done correctly.

**Comment by Sanyen** [comment]
resolved #114
