### ISSUE TITLE
Integrate Sentry support

### ISSUE THREAD

**Issue by webknjaz** [aio-libs/create-aio-app#120]

**Comment by Arfey** [comment]
It's a nice idea 👍

**Comment by 4lovi4** [comment]
Should it be integrated to the generated app with [sentry-sdk](https://docs.sentry.io/platforms/python/aiohttp/)?

**Comment by webknjaz** [comment]
Yes

**Comment by 4lovi4** [comment]
First try https://github.com/aio-libs/create-aio-app/pull/137 check please
