### ISSUE TITLE
Incorrect support version in setup.py

### ISSUE THREAD

**Issue by MaxTyulin** [aio-libs/create-aio-app#144]
setup.py checks if python version is less than 3.5, but the code uses f-strings, which appeared only in version 3.6, as result application doesn't work if python version is less than 3.6. 
The easiest way to fix this is to increase the version in setup.py, but it may be more preferable to replace f-strings with format (for example).

**Comment by Arfey** [comment]
This is a boilerplate for new projects. So, we don't need to support old version of python. PR welcome :)

**Comment by webknjaz** [comment]
All modern distros ship Python 3.7 already. There's no point in expanding the support matrix which also makes it more painful to maintain this.

**Comment by MaxTyulin** [comment]
It is not always possible to have modern distros. I can make the necessary changes, there are only 25 f-strings.

**Comment by webknjaz** [comment]
If you are introducing complexities for maintainers, don't be surprised if you'll end up having to maintain those.

**Comment by MaxTyulin** [comment]
You are right, there is pyenv after all. But if I got an error, that 3.5 is unsupported, right away, it would be more useful :)

**Comment by webknjaz** [comment]
Also there's deadsnakes for debs. And yes, correcting values in `setup.py` would be useful. Three places need updating in `setup.py`: the if-block, then the trove classifier and finally `python_requires`.
