### ISSUE TITLE
consider installing goodfirstissue bot on project/org

### ISSUE THREAD

**Issue by rajatjindal** [aio-libs/create-aio-app#211]
Hi `aio-libs` Team

I've developed a github bot [goodfirstissue](https://github.com/rajatjindal/goodfirstissue) which tweets 'good first issues' via twitter handle [@goodfirstissue](https://twitter.com/goodfirstissue). 

I wanted to see if the team would find it useful to let the bot tweet `goodfirstissues` from this repo/org.

the targeted audience for twitter account are first time contributors, and to encourage open source contributions.

## Some details:

**Permissions this app need:** read permission on issues and metadata.
**Twitter Handle used to tweet:** [@goodfirstissue](https://twitter.com/goodfirstissue)
**Source code of the app/webhook:** https://github.com/rajatjindal/goodfirstissue
**Instructions to install github app**: https://github.com/rajatjindal/goodfirstissue#how-to-install
**Current Users**: https://github.com/rajatjindal/goodfirstissue#current-users

Many thanks for considering.

**Comment by Arfey** [comment]
@webknjaz what do u think about add goodfirstissue bot?

**Comment by webknjaz** [comment]
@Arfey security-wise it's harmless. Community-wise, it may create a flood of newcomers not knowing what they are doing. It's up to you whether to install it, per recent Gh updates you should no longer need org admin approvals to install apps into repos where you are an admin.

**Comment by Arfey** [comment]
@rajatjindal thank u for propose, but it's not interesting for us

**Comment by rajatjindal** [comment]
👍🏻 thanks for reviewing and providing an update though.
