### ISSUE TITLE
Make docker as optional

### ISSUE THREAD

**Issue by Arfey** [aio-libs/create-aio-app#25]
```
reate-aio-app my_project --without-docker
```

the tool should generate project without docker for application and use docker only for `postgres` or `redis`. If  user don't want to use `postgres` and `redis` project shouldn't exist docker.

**Comment by hzlmn** [comment]
Is this option will be exclusive, say if i type
```sh
create-aio-app project --without-docker --redis
```
will be docker added or not?

**Comment by Arfey** [comment]
if u use `--without-docker` flag it's meen that your app will be start without docker. U need to install requirements `pip install -r requirements/development.txt`. But docker will be use for create postgres and redis. If u don't use postgres and redis u don't need docker :)
```
create-aio-app project --without-docker --without-postgres
```
this commend will generate a project without the docker.
