### ISSUE TITLE
Black formatting templates brakes docker image creation

### ISSUE THREAD

**Issue by Alexis117** [aio-libs/create-aio-app#268]
Before the black formatting of the template ```__init__.py``` file, used to have single quotes:

```python
__version__ = '0.0.1'
```

Now it has double quotes and this is breaking the REGEX validation on setup.py.

```python
__version__ = "0.0.1"
```

```python
REGEXP = re.compile(r"^__version__\W*=\W*'([\d.abrc]+)'")
```

**Comment by ShubhamNagure** [comment]
can i contribute this issue?

**Comment by Arfey** [comment]
Hi 🤚

This part already looks great, so i'll close the issue 

https://github.com/aio-libs/create-aio-app/blob/73098eba5213d11037107534365b079a3ec75a86/create_aio_app/template/%7B%7Bcookiecutter.project_name%7D%7D/setup.py#L8

but if u wanna help with current project u can get some else
