### ISSUE TITLE
Questioning architectural decisions wrt skeleton generator

### ISSUE THREAD

**Issue by webknjaz** [aio-libs/create-aio-app#5]
Hi,

Why have own CLI, when [cookiecutter](https://cookiecutter.readthedocs.io) does exactly the same?

I see why you make a dir structure template, but why reinvent the wheel with a renderer?

I suggest using a mainstream thing because otherwise, you end up maintaining yet another template rendering CLI instead of actual useful content (project boilerplate template).

cc @Arfey @jettify @asvetlov

**Comment by jettify** [comment]
From a user perspective, I do not care about, how we template project, I care about the result. There is very little code that does template anyway, easy to read.

So if you have a strong opinion there I guess you can team up with @Arfey and port to cookiecutter. For me project does what I need...

**Comment by asvetlov** [comment]
I have no strong opinion too.
If cookie-cutter simplifies maintenance -- let's consider to use it.
If no -- let's keep everything as is.

**Comment by webknjaz** [comment]
Cookiecutter:
1) Simplifies maintenance
2) Is possibly already installed on machines of ppl who are already used to be starting with project templates
3) Has testing hooks ecosystem for templates
4) Is a de-facto standard

**Comment by asvetlov** [comment]
@Arfey is the project maintainer.
I think he should decide.
My hope is not to touch this repo at all ;)

**Comment by webknjaz** [comment]
Yes, there's conditionals available in cookiecutter + you can define hooks.
For tests I think the plugin is called pytest-cookies (I can look that up in some of my projects if needed).

**Comment by jettify** [comment]
I like having `pip install create-aio-app` is such mode supported by cookiecutter?

**Comment by webknjaz** [comment]
@Arfey https://github.com/audreyr/cookiecutter/issues/723

**Comment by webknjaz** [comment]
@jettify it would be `pip install cookiecutter` and then `cookiecutter install <this repo>`

**Comment by webknjaz** [comment]
I guess you could wrap that into a package, but I don't see a point.

**Comment by asvetlov** [comment]
cookiecutter could be used as a library I guess to keep `create-aio-app` as an executable script

**Comment by webknjaz** [comment]
It would be odd though. Your script would be
```
alias create-aio-app='cookiecutter this-repo'
```

**Comment by asvetlov** [comment]
`pip install <shell alias>`? 8-)

**Comment by Arfey** [comment]
We can create cookiecutter package and for scripts user same as below

```python
from cookiecutter.main import cookiecutter

cookiecutter('cookiecutter-pypackage/create-aio-app')
```

and handle params for configuring of cookiecutter
