### ISSUE TITLE
Create command for update python's dependencies

### ISSUE THREAD

**Issue by Arfey** [aio-libs/create-aio-app#51]
After some time you want to update your python's dependencies in your project.

So, what need to do:

- [ ] create make command for update dependencies inside `requirements/*.txt` files.
- [ ] if template use docker then print messages after update that user need to rebuild container `docker-compose up --build`
- [ ] add describe about this feature in `README.md`

**Comment by tyulpan** [comment]
Take.

**Comment by pmkuny** [comment]
Can we close this issue now that this has been merged?
