### ISSUE TITLE
Add profiling for application

### ISSUE THREAD

**Issue by Arfey** [aio-libs/create-aio-app#58]
If you want to write a fast web application, you sometimes need to profile your application. So it's good feature for `create-api-app`.

So, what need to do:
 - [ ] add make command with https://github.com/benfred/py-spy for docker (make profile)
 - [ ] write some documentations about using this feature

**Comment by Sanyen** [comment]
Hello there @Arfey , I've been trying to figure this out for a day or two now. Would like to work on this.

**Comment by Sanyen** [comment]
So, i kinda got something working. But i'm wondering what would make more sense for other. py-spy record, dump or top. The record feature makes more sense as it can generate an svg file for a visual representation of whats happening. Or, a json file which can be used on speedscope.com for even greater detail. 

Any suggestion? @Arfey

**Comment by Sanyen** [comment]
Let's get this closed
