### ISSUE TITLE
Added pre-commit for running linters

### ISSUE THREAD

**Issue by Arfey** [aio-libs/create-aio-app#67]
This is good feature but we running all linters from docker and it's not fast. Does anyone have any thoughts about this?

**Comment by webknjaz** [comment]
What do you mean? Run it in the CI directly

**Comment by Arfey** [comment]
CI as a solution. Thanks :) I will add ci file for gitlab.

**Comment by Arfey** [comment]
I think that i have better idea. Right now all linters and static checker work with docker. It's works like that because i wonted that user after run `create-ago-app` don't install any additional packages. But, we can add mypy, flake8 and other packages in create-aio-packages to requirement packages in `setup.py`.

**Comment by CatCanCreate** [comment]
Add into .git/hooks/pre-commit:

```
#!/bin/sh
flake8 src/
```
For example?)
