### ISSUE TITLE
Auto spec and validation

### ISSUE THREAD

**Issue by CatCanCreate** [aio-libs/create-aio-app#77]
https://github.com/maximdanilchenko/aiohttp-apispec

Replace trafaret and sphinx with apispec

Middleware for validation input data and access all validated data in route from request['data']
Auto swagger generation with aiohttp-swagger (https://github.com/cr0hn/aiohttp-swagger)

**Comment by Arfey** [comment]
`Build and document REST APIs` - `create-aio-app` it's story not only about rest api.
