### ISSUE TITLE
Run test with params

### ISSUE THREAD

**Issue by Arfey** [aio-libs/create-aio-app#95]
I want to run single test like that

```
docker-compose run -rm test test_mod.py::test_func
```

for that

- [ ] replace command to entrypoint https://github.com/aio-libs/create-aio-app/blob/master/create_aio_app/template/%7B%7Bcookiecutter.project_name%7D%7D/docker-compose.yml#L60
- [ ] replace `make _test`

**Comment by Indoungwe** [comment]
Я буду делать

**Comment by NavrotskyVasyl** [comment]
I'm doing this.

**Comment by 4lovi4** [comment]
Can't find any evidence that is possible to pass the parameters to docker compose this way in line. Is it right? 

May be used something like : `docker-compose run --rm -e TEST=test_mod.py::test_func test ` ?
`

**Comment by Arfey** [comment]
Hello. I have added a description of how this can be done.

U can test `entrypoint` using an example below:

`docker-compose.yaml`
```yaml
version: '3'

services:
    app:
        image: busybox
        entrypoint: 'echo params: '
```

`terminal`

```
>>> dc run app param1 param2 --param3 --param4
>>> params: param1 param2 --param3 --param4
```

Also, u can read about differences between command and entry point in this [article](https://goinbigdata.com/docker-run-vs-cmd-vs-entrypoint/).

This issue is so easy 😀. For solve issue need only follow description step by step.


`description:`

- [ ] replace command to entrypoint https://github.com/aio-libs/create-aio-app/blob/master/create_aio_app/template/%7B%7Bcookiecutter.project_name%7D%7D/docker-compose.yml#L60
- [ ] replace `make _test`

If people have problem with understand of this behavior i think this need to be describe into the docs. So, to the description above need to add more one item.

- [ ] add description about that into the `docs`

**Comment by 4lovi4** [comment]
Think I've got the point :wink:  Thx. See it done soon.
